### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fowl2** [endorph-soft/wpplus#58]
Hiya, thanks for the great work on WP+!

Just wondering what the license is? 

I'd suggest the MIT license - there's some simple steps to apply it on the GitHub docs here: [Adding a license to a repository](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by phyco1991** [comment]
Hey James, No worries at all thanks for the feedback.

Regarding the license I have to say I've never really considered that, I will look into over this weekend and come to some kind of decision.

As for your pull request the feature changes are great and I will definitely integrate into the next build/credit you for them, however I can't merge them without the other appropriate changes required to release a new version, the changelog needs to be updated as well as the versioning being brought forward and storage version changed so the scripts auto update feature behaves appropriately. I will get all of this put into a readme at some point.

Cheers
